# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chacha < Formula
  desc ""
  homepage ""
  version "0.8.0"
  license "FSL-1.1-Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cirruslabs/chacha/releases/download/v0.8.0/chacha-darwin-amd64.tar.gz"
      sha256 "026f675f206a9e9717956d1926272f3c12ccd5cd3310678663bb09c04e1fdf10"

      def install
        bin.install "chacha"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cirruslabs/chacha/releases/download/v0.8.0/chacha-darwin-arm64.tar.gz"
      sha256 "74878a0739ffd6822df46912fb441012452930f02a109ea287ba30ea06544588"

      def install
        bin.install "chacha"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cirruslabs/chacha/releases/download/v0.8.0/chacha-linux-amd64.tar.gz"
        sha256 "e4030161c6961f8d58ff6dc588b03a8f83b84a7d8f96ba3df97195791a93378f"

        def install
          bin.install "chacha"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cirruslabs/chacha/releases/download/v0.8.0/chacha-linux-arm64.tar.gz"
        sha256 "2000dc1a0456229471192519fa17fb2a115b4550a033d56a77934edbc73087d1"

        def install
          bin.install "chacha"
        end
      end
    end
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
