# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chacha < Formula
  desc ""
  homepage ""
  version "0.4.0"
  license "FSL-1.1-Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cirruslabs/chacha/releases/download/v0.4.0/chacha-darwin-amd64.tar.gz"
      sha256 "cd3e27dd2eeb6b30e8fad2365638a46e7dfbbcf6ca037bf36cacd4fdc14181f1"

      def install
        bin.install "chacha"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cirruslabs/chacha/releases/download/v0.4.0/chacha-darwin-arm64.tar.gz"
      sha256 "22d46d142efb0f14f4cbcc7a31305815e3f06852f59cd8666221baacb33ff743"

      def install
        bin.install "chacha"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cirruslabs/chacha/releases/download/v0.4.0/chacha-linux-amd64.tar.gz"
        sha256 "71260443839dcdae6aeda725654db65e72bd2ca7714dc1dd3f4243526c2b732a"

        def install
          bin.install "chacha"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cirruslabs/chacha/releases/download/v0.4.0/chacha-linux-arm64.tar.gz"
        sha256 "6eb5535d491784939408e6168713135c6e8977ba1010cb4d4a7a0db5be0537e4"

        def install
          bin.install "chacha"
        end
      end
    end
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
