# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chacha < Formula
  desc ""
  homepage ""
  version "0.13.0"
  license "FSL-1.1-Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cirruslabs/chacha/releases/download/v0.13.0/chacha-darwin-amd64.tar.gz"
      sha256 "9c0e4515bb07f26d2c80b5767d58fd6ce4319d8fe85b4ce5fd22cd5f400b10b7"

      def install
        bin.install "chacha"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cirruslabs/chacha/releases/download/v0.13.0/chacha-darwin-arm64.tar.gz"
      sha256 "7e0d89526b28fb4dd2cd4dd0ecfca9857d02f56f5d3aec0dd1a925ddd165427f"

      def install
        bin.install "chacha"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cirruslabs/chacha/releases/download/v0.13.0/chacha-linux-amd64.tar.gz"
        sha256 "87ec73bd6349f097a04afe4aea4c121225032143ac20b9719ecc7b2f049d2564"

        def install
          bin.install "chacha"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cirruslabs/chacha/releases/download/v0.13.0/chacha-linux-arm64.tar.gz"
        sha256 "11a4cd5424a185f7aae3cb520055ae9c015b334465f151dba7d1d2a6681e212b"

        def install
          bin.install "chacha"
        end
      end
    end
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
