# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cirrus < Formula
  desc "CLI for running Cirrus Tasks locally in Docker containers"
  homepage "https://github.com/cirruslabs/cirrus-cli"
  version "0.85.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cirruslabs/cirrus-cli/releases/download/v0.85.0/cirrus-darwin-arm64.tar.gz"
      sha256 "56b331410ac51c22ac0c93df3d3250987a15766d4b8cab356a1afd59ef2ef395"

      def install
        bin.install "cirrus"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cirruslabs/cirrus-cli/releases/download/v0.85.0/cirrus-darwin-amd64.tar.gz"
      sha256 "c20c9664bcf98eec853a2db8caadf4ea8709efc1232427674a771774a334b281"

      def install
        bin.install "cirrus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/cirruslabs/cirrus-cli/releases/download/v0.85.0/cirrus-linux-arm.tar.gz"
      sha256 "9520a3d9302e56a37711120922e738c5b8d07e87befce7e43ef3e80372d6d5b0"

      def install
        bin.install "cirrus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cirruslabs/cirrus-cli/releases/download/v0.85.0/cirrus-linux-arm64.tar.gz"
      sha256 "fadd439c9d2d54647758faa4fc846c4846e7dec601049423363cc812802633c3"

      def install
        bin.install "cirrus"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cirruslabs/cirrus-cli/releases/download/v0.85.0/cirrus-linux-amd64.tar.gz"
      sha256 "73fbcd36bb5730a9d7d2ef1bb720ea8b9c602d00d20969a0265c934678a61b34"

      def install
        bin.install "cirrus"
      end
    end
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
