# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cirrus < Formula
  desc "CLI for running Cirrus Tasks locally in Docker containers"
  homepage "https://github.com/cirruslabs/cirrus-cli"
  version "0.82.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cirruslabs/cirrus-cli/releases/download/v0.82.0/cirrus-darwin-arm64.tar.gz"
      sha256 "bb1fc530ceb6987cd30d77ce531b58270c2f39db79161c464b41dbba30f94816"

      def install
        bin.install "cirrus"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cirruslabs/cirrus-cli/releases/download/v0.82.0/cirrus-darwin-amd64.tar.gz"
      sha256 "399c948dfb2525372cfa814eafcee2d7addf73798f256ac3e8733b9cd1f6e503"

      def install
        bin.install "cirrus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/cirruslabs/cirrus-cli/releases/download/v0.82.0/cirrus-linux-arm.tar.gz"
      sha256 "85ea00e691e5c360097ecc8043abea99b6c475ca5bb899700b633a2429d30089"

      def install
        bin.install "cirrus"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cirruslabs/cirrus-cli/releases/download/v0.82.0/cirrus-linux-amd64.tar.gz"
      sha256 "4ef2073e8cd01b24c96e6c43945aa9a23d9af5274955937b46cb5db21abce6af"

      def install
        bin.install "cirrus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cirruslabs/cirrus-cli/releases/download/v0.82.0/cirrus-linux-arm64.tar.gz"
      sha256 "566169087c19f48f8abd9bc9f79dee44ec937aa463b46dc162b0c2116a26479a"

      def install
        bin.install "cirrus"
      end
    end
  end

  def caveats; <<~EOS
    See the Github repository for more information
  EOS
  end
end
