# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cirrus < Formula
  desc ""
  homepage ""
  version "0.114.2"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cirruslabs/cirrus-cli/releases/download/v0.114.2/cirrus-darwin-amd64.tar.gz"
      sha256 "c68fdf0643c8edbcdb1e05ee9091d1618133c7110705387ea1a8873ff7ad2c8a"

      def install
        bin.install "cirrus"
        generate_completions_from_executable(bin/"cirrus", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cirruslabs/cirrus-cli/releases/download/v0.114.2/cirrus-darwin-arm64.tar.gz"
      sha256 "e0ffb0488d1e1570ff61f5856c5649fca8c407a13e6b0764f09e5ea4063e5e8b"

      def install
        bin.install "cirrus"
        generate_completions_from_executable(bin/"cirrus", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cirruslabs/cirrus-cli/releases/download/v0.114.2/cirrus-linux-amd64.tar.gz"
      sha256 "058567846ac5d5e779301f7b274274ebc5ffe8dadba20bb0d2a80915d090c757"

      def install
        bin.install "cirrus"
        generate_completions_from_executable(bin/"cirrus", "completion")
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/cirruslabs/cirrus-cli/releases/download/v0.114.2/cirrus-linux-arm.tar.gz"
      sha256 "58ae8ec61c555c3d0643594bf6606135cd48b668f5eac27e806d033973c33b90"

      def install
        bin.install "cirrus"
        generate_completions_from_executable(bin/"cirrus", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cirruslabs/cirrus-cli/releases/download/v0.114.2/cirrus-linux-arm64.tar.gz"
      sha256 "412095f04cd595e9fb0d0f4770ed47de35e9337e1d0e27ea404c0065c99f25cf"

      def install
        bin.install "cirrus"
        generate_completions_from_executable(bin/"cirrus", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
