# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabTartExecutor < Formula
  desc "GitLab Runner Executor to run jobs inside isolated Tart VMs"
  homepage "https://github.com/cirruslabs/gitlab-tart-executor"
  version "1.23.0"

  depends_on "cirruslabs/cli/tart"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/cirruslabs/gitlab-tart-executor/releases/download/1.23.0/gitlab-tart-executor-darwin-arm64.tar.gz"
    sha256 "f164836c307b7c7560fdbb9c730dbcbc21e787fcbf306a011b9dc76b86562667"

    def install
      bin.install "gitlab-tart-executor"
    end
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
