# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabTartExecutor < Formula
  desc "GitLab Runner Executor to run jobs inside isolated Tart VMs"
  homepage "https://github.com/cirruslabs/gitlab-tart-executor"
  version "1.25.1"

  depends_on "cirruslabs/cli/tart"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/cirruslabs/gitlab-tart-executor/releases/download/1.25.1/gitlab-tart-executor-darwin-arm64.tar.gz"
    sha256 "c44118fa923c6fdd58d0688398cf40e4c9a0a61764d2b073e7d21a6f53e8423f"

    def install
      bin.install "gitlab-tart-executor"
    end
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
