# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mtell < Formula
  desc "CLI to tell a machine to do something over VNC"
  homepage "https://github.com/cirruslabs/mtell"
  version "0.4.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/cirruslabs/mtell/releases/download/0.4.1/mtell-darwin-amd64.tar.gz"
    sha256 "e6a54a8de54e18b950d862ee71d22f077e008d61cdd9eb849ddf5d441b9b6514"

    define_method(:install) do
      bin.install "mtell"
      generate_completions_from_executable(bin/"mtell", "completion")
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/cirruslabs/mtell/releases/download/0.4.1/mtell-darwin-arm64.tar.gz"
    sha256 "ea33559f2173fd463ab381f7d3f70716a7c6b1b442bd363103ccf0a5fe2869d9"

    define_method(:install) do
      bin.install "mtell"
      generate_completions_from_executable(bin/"mtell", "completion")
    end
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
