# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mtell < Formula
  desc "CLI to tell a machine to do something over VNC"
  homepage "https://github.com/cirruslabs/mtell"
  version "0.2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/cirruslabs/mtell/releases/download/0.2.0/mtell-darwin-amd64.tar.gz"
    sha256 "a0be75d1612d549814fa68987f7bfcd71b1e56d793b65f21a5e12fa48a2ab7ba"

    define_method(:install) do
      bin.install "mtell"
      generate_completions_from_executable(bin/"mtell", "completion")
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/cirruslabs/mtell/releases/download/0.2.0/mtell-darwin-arm64.tar.gz"
    sha256 "4008bbeea4bf2d06b9e8eea56b41a399e04c35b380e62b14a0c39cac9d9ec0ca"

    define_method(:install) do
      bin.install "mtell"
      generate_completions_from_executable(bin/"mtell", "completion")
    end
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
