# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mtell < Formula
  desc "CLI to tell a machine to do something over VNC"
  homepage "https://github.com/cirruslabs/mtell"
  version "0.4.2"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/cirruslabs/mtell/releases/download/0.4.2/mtell-darwin-amd64.tar.gz"
    sha256 "5b378c382285a9e7bdc9ac105b4e88a0c91067cfe57671979dd9c454aaaa61da"

    define_method(:install) do
      bin.install "mtell"
      generate_completions_from_executable(bin/"mtell", "completion")
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/cirruslabs/mtell/releases/download/0.4.2/mtell-darwin-arm64.tar.gz"
    sha256 "00bb54471369c23b75e8aa249b1f7c4c85edc2ae4eea8e01f2616f560e7aa01f"

    define_method(:install) do
      bin.install "mtell"
      generate_completions_from_executable(bin/"mtell", "completion")
    end
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
