# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OmniCache < Formula
  desc ""
  homepage ""
  version "0.7.0"
  license "FSL-1.1-ALv2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cirruslabs/omni-cache/releases/download/v0.7.0/omni-cache-darwin-amd64.tar.gz"
      sha256 "b500f59f7cbbf58d5e8a465e8afa7c655a72f10afc72d5fe03d2edc5c05f310f"

      def install
        bin.install "omni-cache"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cirruslabs/omni-cache/releases/download/v0.7.0/omni-cache-darwin-arm64.tar.gz"
      sha256 "72e798ff93190e8415d17416d6ef973e106c8a373fed6c36b807e93f467b64b3"

      def install
        bin.install "omni-cache"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cirruslabs/omni-cache/releases/download/v0.7.0/omni-cache-linux-amd64.tar.gz"
      sha256 "b682c4a795e78f7a110ab9f9ec758df20b7d921c981843b3fbebb5292599c357"
      def install
        bin.install "omni-cache"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/cirruslabs/omni-cache/releases/download/v0.7.0/omni-cache-linux-arm.tar.gz"
      sha256 "032a443d58c7938a53c846f3e5daee7ae846d4495f536918f68432cc69ea9249"
      def install
        bin.install "omni-cache"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cirruslabs/omni-cache/releases/download/v0.7.0/omni-cache-linux-arm64.tar.gz"
      sha256 "01839645f75afc9143ca36f59b752e0782931a961c4b3d9b5d5d4ed7fb0ff259"
      def install
        bin.install "omni-cache"
      end
    end
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
