# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orchard < Formula
  desc "Orchestrator for running Tart Virtual Machines on a cluster of Apple Silicon devices"
  homepage "https://github.com/cirruslabs/orchard"
  version "0.19.1"

  on_macos do
    on_intel do
      url "https://github.com/cirruslabs/orchard/releases/download/0.19.1/orchard-darwin-amd64.tar.gz"
      sha256 "50d7da1ed1c62186be9f0273f164afd083ad7eb7b04b7a9a52412b72290baf79"

      def install
        bin.install "orchard"
        generate_completions_from_executable(bin/"orchard", "completion")
      end
    end
    on_arm do
      url "https://github.com/cirruslabs/orchard/releases/download/0.19.1/orchard-darwin-arm64.tar.gz"
      sha256 "2b80d280e6eca7be6ee7f9e10412a072b58703a3f3e8054b829b56747a52ef9e"

      def install
        bin.install "orchard"
        generate_completions_from_executable(bin/"orchard", "completion")
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cirruslabs/orchard/releases/download/0.19.1/orchard-linux-amd64.tar.gz"
        sha256 "4ea07b9870c9aa91f49f5cbfe7db5e94a23dc56e24d1d9c89c74cc74a7bee670"

        def install
          bin.install "orchard"
          generate_completions_from_executable(bin/"orchard", "completion")
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cirruslabs/orchard/releases/download/0.19.1/orchard-linux-arm64.tar.gz"
        sha256 "20c5bcb878c591c749f8c34bf48da3603164445d74a4f800621b202f9e499a84"

        def install
          bin.install "orchard"
          generate_completions_from_executable(bin/"orchard", "completion")
        end
      end
    end
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
