# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orchard < Formula
  desc "Orchestrator for running Tart Virtual Machines on a cluster of Apple Silicon devices"
  homepage "https://github.com/cirruslabs/orchard"
  version "0.19.0"

  on_macos do
    on_intel do
      url "https://github.com/cirruslabs/orchard/releases/download/0.19.0/orchard-darwin-amd64.tar.gz"
      sha256 "150a1cda035ff4dac19d5dbabde77c9f67a43f884e6170a559f4ce1af125cf7c"

      def install
        bin.install "orchard"
        generate_completions_from_executable(bin/"orchard", "completion")
      end
    end
    on_arm do
      url "https://github.com/cirruslabs/orchard/releases/download/0.19.0/orchard-darwin-arm64.tar.gz"
      sha256 "e43c414e1a238ee488bb00931f226f885334cf76ebdad2ee9fc5706a85fba081"

      def install
        bin.install "orchard"
        generate_completions_from_executable(bin/"orchard", "completion")
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cirruslabs/orchard/releases/download/0.19.0/orchard-linux-amd64.tar.gz"
        sha256 "0264563b2bb675808c9428412a0b364d68a527d1e29ef8cec939a54d828f97a4"

        def install
          bin.install "orchard"
          generate_completions_from_executable(bin/"orchard", "completion")
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cirruslabs/orchard/releases/download/0.19.0/orchard-linux-arm64.tar.gz"
        sha256 "0b2f0baee330f757a643d8b3b162cd254c65b26b5b9ef3a29ad3170ceeb91230"

        def install
          bin.install "orchard"
          generate_completions_from_executable(bin/"orchard", "completion")
        end
      end
    end
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
