# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orchard < Formula
  desc "Orchestrator for running Tart Virtual Machines on a cluster of Apple Silicon devices"
  homepage "https://github.com/cirruslabs/orchard"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cirruslabs/orchard/releases/download/0.1.0/orchard-darwin-arm64.tar.gz"
      sha256 "00f61f55f3ead3e64973d7a54c20c7247392531673e914fb93ad4e713ccd4e0d"

      def install
        bin.install "orchard"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cirruslabs/orchard/releases/download/0.1.0/orchard-darwin-amd64.tar.gz"
      sha256 "23e1e61e2882ffd62565538ea53324a7de96b37e5a5c520901a6ec471de20178"

      def install
        bin.install "orchard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cirruslabs/orchard/releases/download/0.1.0/orchard-linux-arm64.tar.gz"
      sha256 "6fea4d0b63212b453fcf4ced0d6197b1cce5504f6c21d888509cd7827f96f4e7"

      def install
        bin.install "orchard"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cirruslabs/orchard/releases/download/0.1.0/orchard-linux-amd64.tar.gz"
      sha256 "05dce61d423942f2fc9c551d16e884d9b9007b91511ff43bad5b72249469b999"

      def install
        bin.install "orchard"
      end
    end
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
