# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SetupInfoGenerator < Formula
  desc ""
  homepage ""
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cirruslabs/setup-info-generator/releases/download/0.1.1/setup-info-generator-darwin-amd64.tar.gz"
      sha256 "034811df731f585f297fcf49d468354146915936d99e7bb22ffd867b562d6fac"

      def install
        bin.install "setup-info-generator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cirruslabs/setup-info-generator/releases/download/0.1.1/setup-info-generator-darwin-arm64.tar.gz"
      sha256 "0a337bf18d7379bb7e182f50b6fa5d5e8c0b22cc459e221fdb6baa7f0161a07e"

      def install
        bin.install "setup-info-generator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cirruslabs/setup-info-generator/releases/download/0.1.1/setup-info-generator-linux-amd64.tar.gz"
        sha256 "94191a295936647a7b2d2011877c725a44b9e33eb612533fc72a2c496b691c66"

        def install
          bin.install "setup-info-generator"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cirruslabs/setup-info-generator/releases/download/0.1.1/setup-info-generator-linux-arm64.tar.gz"
        sha256 "82f09085fe6117127720648117d2d87c18141356ab319c345503f45a836dd5da"

        def install
          bin.install "setup-info-generator"
        end
      end
    end
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
