# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Softnet < Formula
  desc "Software networking with isolation for Tart"
  homepage "https://github.com/cirruslabs/softnet"
  version "0.16.0"
  depends_on :macos

  url "https://github.com/cirruslabs/softnet/releases/download/0.16.0/softnet.tar.gz"
  sha256 "8a7d36571e42506860afbcee1d13f32aae577e31b516912013b8ad7a956d4b63"

  def install
    bin.install "softnet"
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
