# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Softnet < Formula
  desc "Software networking with isolation for Tart"
  homepage "https://github.com/cirruslabs/softnet"
  version "0.6.0"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cirruslabs/softnet/releases/download/0.6.0/softnet.tar.gz"
      sha256 "eb028b916432392f5bc0f5c0679034d8616b1521489a1978a015814ff269d649"

      def install
        bin.install "softnet"
      end
    end
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
