# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TartGuestAgent < Formula
  desc "Guest agent for Tart VMs"
  homepage "https://github.com/cirruslabs/tart-guest-agent"
  version "0.5.0"
  license "FSL-1.1-Apache-2.0"

  on_macos do
    url "https://github.com/cirruslabs/tart-guest-agent/releases/download/v0.5.0/tart-guest-agent-darwin-all.tar.gz"
    sha256 "0856c7c23c765302bcd95b92fdbeaf9ab435fc432fcb1f094bcbe4d579e8e99c"

    def install
      bin.install "tart-guest-agent"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/cirruslabs/tart-guest-agent/releases/download/v0.5.0/tart-guest-agent-linux-amd64.tar.gz"
      sha256 "fbdcdd085e4c13a7d63c3020de35e3d5d45b231197eb1838387583aae8d6b73f"
      def install
        bin.install "tart-guest-agent"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/cirruslabs/tart-guest-agent/releases/download/v0.5.0/tart-guest-agent-linux-arm64.tar.gz"
      sha256 "0caf9e4502df8a9ed53f7f272b7b320ffef6b736a65f016487586e5f2f79977b"
      def install
        bin.install "tart-guest-agent"
      end
    end
  end
end
