# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tart < Formula
  desc "Run macOS VMs on Apple Silicon"
  homepage "https://github.com/cirruslabs/tart"
  version "0.9.1"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cirruslabs/tart/releases/download/0.9.1/tart.tar.gz"
      sha256 "06f4c05cae802fb8f63fcfcd7437a3975a539f92c624e764ba44756f3c3dd87b"

      def install
        bin.install "tart"
      end
    end
  end

  depends_on :macos => :monterey

  def caveats; <<~EOS
    See the Github repository for more information
  EOS
  end
end
