# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TartGuestAgent < Formula
  desc "Guest agent for Tart VMs"
  homepage "https://github.com/cirruslabs/tart-guest-agent"
  version "0.7.0"
  license "FSL-1.1-Apache-2.0"

  on_macos do
    url "https://github.com/cirruslabs/tart-guest-agent/releases/download/v0.7.0/tart-guest-agent-darwin-all.tar.gz"
    sha256 "f4fbf7c0c8e6bb1e83eaa6bfdde259965029b1140e1d744868941c812fed4f5a"

    def install
      bin.install "tart-guest-agent"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/cirruslabs/tart-guest-agent/releases/download/v0.7.0/tart-guest-agent-linux-amd64.tar.gz"
      sha256 "722593026c28ac1a6dc6a531d8bdcd64f65b209e8ba6f5c6c7549017f4f90cc3"
      def install
        bin.install "tart-guest-agent"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/cirruslabs/tart-guest-agent/releases/download/v0.7.0/tart-guest-agent-linux-arm64.tar.gz"
      sha256 "e51837460034be51b0396684d51e3e139080f25f71e951db175d79608955e9ff"
      def install
        bin.install "tart-guest-agent"
      end
    end
  end
end
