# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tart < Formula
  desc "Run macOS and Linux VMs on Apple Hardware"
  homepage "https://github.com/cirruslabs/tart"
  version "2.8.1"
  license "Fair Source"

  depends_on "cirruslabs/cli/softnet"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/cirruslabs/tart/releases/download/2.8.1/tart-arm64.tar.gz"
    sha256 "bfead3164d266324efa5fa133eff4b30ee29654a524dfa93e1836f1a406ed539"

    def install
      libexec.install Dir["*"]
      bin.write_exec_script "#{libexec}/tart.app/Contents/MacOS/tart"
      generate_completions_from_executable(libexec/"tart.app/Contents/MacOS/tart", "--generate-completion-script")
    end
  end
  if Hardware::CPU.intel?
    url "https://github.com/cirruslabs/tart/releases/download/2.8.1/tart-amd64.tar.gz"
    sha256 "b737c07f50b9d5b9a954266906c99ceb82268f3366ddce186a0ba6eef1892572"

    def install
      libexec.install Dir["*"]
      bin.write_exec_script "#{libexec}/tart.app/Contents/MacOS/tart"
      generate_completions_from_executable(libexec/"tart.app/Contents/MacOS/tart", "--generate-completion-script")
    end
  end

  depends_on :macos => :ventura

  def caveats
    <<~EOS
      See the GitHub repository for more information
    EOS
  end
end
