# This file was generated by GoReleaser. DO NOT EDIT.
cask "chamber" do
  name "chamber"
  desc ""
  homepage ""
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chamber"
  depends_on formula: [
      "cirruslabs/cli/tart",
    ]

  on_macos do
    on_intel do
      url "https://github.com/cirruslabs/chamber/releases/download/v#{version}/chamber-darwin-amd64.tar.gz"
      sha256 "a27cdc5e3fb63222ecf9e085105c960d5905db147f581cab0fd07f27e05e5eb2"
    end
    on_arm do
      url "https://github.com/cirruslabs/chamber/releases/download/v#{version}/chamber-darwin-arm64.tar.gz"
      sha256 "90bedd74f8bb9d2cb0a9f936cbd6b797bdb69a940fd430f38765d303fd039c57"
    end
  end

  caveats do
    "See the Github repository for more information"
  end

  # No zap stanza required
end
