# This file was generated by GoReleaser. DO NOT EDIT.
cask "chamber" do
  desc ""
  homepage ""
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chamber"
  depends_on formula: [
      "cirruslabs/cli/tart",
    ]

  on_macos do
    on_intel do
      url "https://github.com/cirruslabs/chamber/releases/download/0.1.0/chamber-darwin-amd64.tar.gz"
      sha256 "6774d512c8268eb0dcfbba76c84e3fbe60e19bee877abc8b506545737f5c1456"
    end
    on_arm do
      url "https://github.com/cirruslabs/chamber/releases/download/0.1.0/chamber-darwin-arm64.tar.gz"
      sha256 "10713227329044f4f76166bc5665c829c105e5f4c766ddde1938589100d2f51a"
    end
  end

  caveats do
    "See the Github repository for more information"
  end

  # No zap stanza required
end
